name: Deploy
on:
  push:
    branches: [main]
permissions:
  contents: read
  id-token: write
jobs:
  deploy:
    uses: JonasLoos/deployer/.github/workflows/deploy.yml@v1
    with:
      domain: qr.jloos.de
      healthcheck: /
